formatter: markdown document

version: ""
header-from: .config/header.txt

sections:
  show:
    - header
    - inputs
    - outputs

content: |-
  {{ .Header }}

  {{ .Inputs }}

  {{ .Outputs }}

output:
  file: ""
  mode: inject
  template: |-
    <!-- BEGIN_TF_DOCS -->
    {{ .Content }}
    <!-- END_TF_DOCS -->

output-values:
  enabled: false

sort:
  enabled: true
  by: required

settings:
  anchor: true
  default: true
  description: true
  escape: true
  hide-empty: false
  html: true
  indent: 2
  lockfile: false
  required: true
  sensitive: true
  type: true