#Context
output "context" {
  description = "Context generated by input parameters"
  value       = local.context
}

#Direct Data Access
output "all_sub01" {
  description = "Values for all Subsidiary 01 environments"
  value       = local.all_sub01
}
output "all_sub02" {
  description = "Values for all Subsidiary 02 environments"
  value       = local.all_sub02
}
output "all_sub03" {
  description = "Values for all Subsidiary 03 environments"
  value       = local.all_sub03
}
output "all_sub04" {
  description = "Values for all Subsidiary 04 environments"
  value       = local.all_sub04
}
output "all_sub05" {
  description = "Values for all Subsidiary 05 environments"
  value       = local.all_sub05
}

#Common
output "subsidiary" {
  value       = local.subsidiary
  description = "Subsidiary Code"
}
output "cloud" {
  value       = local.cloud
  description = "Cloud Provider"
}
output "environment" {
  value       = local.environment
  description = "Environment"
}
output "region" {
  value       = local.region
  description = "Cloud Region"
}
output "project" {
  value       = local.project
  description = "Project Code"
}
output "tags" {
  value       = local.tags
  description = "Resource Tags"
}