#Context
output "context" {
  description = "Context generated by input parameters"
  value       = local.context
}

#Direct Data Access
output "all_choco" {
  description = "Values for all Chocolate Factory environments"
  value       = local.all_choco
}
output "all_candy" {
  description = "Values for all Candy Shop environments"
  value       = local.all_candy
}
output "all_icecream" {
  description = "Values for all Icecream Industries environments"
  value       = local.all_icecream
}
output "all_muffin" {
  description = "Values for all Muffin Manufactures environments"
  value       = local.all_muffin
}
output "all_waffel" {
  description = "Values for all Waffel Works environments"
  value       = local.all_waffel
}

#Common
output "subsidiary" {
  value       = local.subsidiary
  description = "Subsidiary Code"
}
output "cloud" {
  value       = local.cloud
  description = "Cloud Provider"
}
output "environment" {
  value       = local.environment
  description = "Environment"
}
output "region" {
  value       = local.region
  description = "Cloud Region"
}
output "project" {
  value       = local.project
  description = "Project Code"
}
output "tags" {
  value       = local.tags
  description = "Resource Tags"
}