formatter: markdown document

version: ""
header-from: .config/header.txt
footer-from: .config/footer.txt


sections:
  show:
    - header
    - footer
    - inputs
    - outputs
    - requirements
    - providers
    - resources

content: |-
  {{ .Header }}

  {{ .Requirements }}

  {{ .Providers }}

  ## Examples
  
  ### Example for Brussels Chocolate Factory
  ```hcl
  {{ include "examples/01-choco/test.tf" }}
  ```

  ### Example for Cologne Candy Shop
  ```hcl
  {{ include "examples/02-candy/test.tf" }}
  ```

  ### Example for Istanbul Icecream Industries
  ```hcl
  {{ include "examples/03-icecream/test.tf" }}
  ```

  ### Example for London Muffin Manufactures
  ```hcl
  {{ include "examples/04-muffin/test.tf" }}
  ```

  ### Example for Amsterdam Waffel Works
  ```hcl
  {{ include "examples/05-waffel/test.tf" }}
  ```

  {{ .Resources }}

  {{ .Inputs }}

  {{ .Outputs }}

  {{ .Footer }}

output:
  file: ""
  mode: inject
  template: |-
    <!-- BEGIN_TF_DOCS -->
    {{ .Content }}
    <!-- END_TF_DOCS -->

output-values:
  enabled: false

sort:
  enabled: true
  by: required

settings:
  anchor: true
  default: true
  description: true
  escape: true
  hide-empty: false
  html: true
  indent: 2
  lockfile: false
  required: true
  sensitive: true
  type: true